package com.example.ui.localization

import com.example.data.AppLanguage

enum class TransKey {
    APP_TITLE,
    APP_SUBTITLE,
    LOGIN_TITLE,
    LOGIN_SUBTITLE,
    USERNAME_LABEL,
    PASSWORD_LABEL,
    CONFIRM_PASSWORD_LABEL,
    BTN_LOGIN,
    BTN_REGISTER,
    GOTO_REGISTER,
    GOTO_LOGIN,
    ERROR_EMPTY_FIELDS,
    ERROR_PASS_MISMATCH,
    ERROR_USER_EXISTS,
    ERROR_INVALID_CREDENTIALS,
    SUCCESS_REGISTER,
    SUCCESS_LOGIN,
    WELCOME_BACK,
    LOGOUT,
    LEVEL,
    SETTINGS,
    SELECT_THEME,
    SELECT_LANG,
    SIGMA_LEVEL_BAR,
    SIGMA_STREAK,
    MOTIVATION_BANNER,
    HABIT_TRACKER_TITLE,
    ADD_HABIT_TITLE,
    EDIT_HABIT_TITLE,
    HABIT_NAME_LABEL,
    HABIT_DESC_LABEL,
    BTN_SAVE,
    BTN_CANCEL,
    BTN_DELETE,
    BTN_EDIT,
    DAILY_PROGRESS,
    WEEKLY_PROGRESS,
    MONTHLY_PROGRESS,
    HABIT_STATS,
    STREAK_DAYS,
    TOTAL_COMPLETIONS,
    COMPLETION_RATE,
    NO_HABITS_YET,
    CONFIRM_DELETE_TITLE,
    CONFIRM_DELETE_MSG
}

object AppLocalizations {
    private val translations = mapOf(
        AppLanguage.INDONESIA to mapOf(
            TransKey.APP_TITLE to "Sigma Habit Ultimate",
            TransKey.APP_SUBTITLE to "Level-Up Kedisiplinanmu ke Tingkat Dewa",
            TransKey.LOGIN_TITLE to "Masuk Akal Sigma",
            TransKey.LOGIN_SUBTITLE to "Silakan login menggunakan akun lokalmu.",
            TransKey.USERNAME_LABEL to "Nama Pengguna (Username)",
            TransKey.PASSWORD_LABEL to "Kata Sandi (Password)",
            TransKey.CONFIRM_PASSWORD_LABEL to "Konfirmasi Kata Sandi",
            TransKey.BTN_LOGIN to "MASUK (LOGIN)",
            TransKey.BTN_REGISTER to "DAFTAR (REGISTER)",
            TransKey.GOTO_REGISTER to "Belum punya akun? Daftar Sekarang",
            TransKey.GOTO_LOGIN to "Sudah punya akun? Masuk Sekarang",
            TransKey.ERROR_EMPTY_FIELDS to "Harap isi semua input field!",
            TransKey.ERROR_PASS_MISMATCH to "Konfirmasi password tidak cocok!",
            TransKey.ERROR_USER_EXISTS to "Username sudah terdaftar!",
            TransKey.ERROR_INVALID_CREDENTIALS to "Username atau password salah!",
            TransKey.SUCCESS_REGISTER to "Registrasi Akun Berhasil!",
            TransKey.SUCCESS_LOGIN to "Selamat Datang di Sigma Habit!",
            TransKey.WELCOME_BACK to "Selamat Datang,",
            TransKey.LOGOUT to "Keluar Akun",
            TransKey.LEVEL to "Level Sigma",
            TransKey.SETTINGS to "Pengaturan UI",
            TransKey.SELECT_THEME to "Pilih Tema Visual",
            TransKey.SELECT_LANG to "Pilih Bahasa",
            TransKey.SIGMA_LEVEL_BAR to "Kemajuan Sigma",
            TransKey.SIGMA_STREAK to "Buntelan Streak (Fokus Harian)",
            TransKey.MOTIVATION_BANNER to "Disiplin adalah pembeda utama antara pecundang dan pemenang.",
            TransKey.HABIT_TRACKER_TITLE to "Pelacak Kebiasaan",
            TransKey.ADD_HABIT_TITLE to "Tambah Kebiasaan",
            TransKey.EDIT_HABIT_TITLE to "Edit Kebiasaan",
            TransKey.HABIT_NAME_LABEL to "Nama Kebiasaan",
            TransKey.HABIT_DESC_LABEL to "Deskripsi / Catatan",
            TransKey.BTN_SAVE to "Simpan",
            TransKey.BTN_CANCEL to "Batal",
            TransKey.BTN_DELETE to "Hapus",
            TransKey.BTN_EDIT to "Ubah",
            TransKey.DAILY_PROGRESS to "Kemajuan Harian",
            TransKey.WEEKLY_PROGRESS to "Kemajuan Mingguan",
            TransKey.MONTHLY_PROGRESS to "Kemajuan Bulanan",
            TransKey.HABIT_STATS to "Statistik Kebiasaan",
            TransKey.STREAK_DAYS to "Streak Beruntun",
            TransKey.TOTAL_COMPLETIONS to "Total Selesai",
            TransKey.COMPLETION_RATE to "Rasio Keberhasilan",
            TransKey.NO_HABITS_YET to "Belum ada kebiasaan. Tekan '+' di atas untuk menambahkan!",
            TransKey.CONFIRM_DELETE_TITLE to "Hapus Kebiasaan?",
            TransKey.CONFIRM_DELETE_MSG to "Apakah Anda yakin ingin menghapus kebiasaan ini secara permanen?"
        ),
        AppLanguage.ENGLISH to mapOf(
            TransKey.APP_TITLE to "Sigma Habit Ultimate",
            TransKey.APP_SUBTITLE to "Level-Up Your Discipline to God Level",
            TransKey.LOGIN_TITLE to "Sigma Authentication",
            TransKey.LOGIN_SUBTITLE to "Please log in using your local account.",
            TransKey.USERNAME_LABEL to "Username",
            TransKey.PASSWORD_LABEL to "Password",
            TransKey.CONFIRM_PASSWORD_LABEL to "Confirm Password",
            TransKey.BTN_LOGIN to "LOG IN",
            TransKey.BTN_REGISTER to "REGISTER",
            TransKey.GOTO_REGISTER to "Don't have an account? Register Now",
            TransKey.GOTO_LOGIN to "Already have an account? Log In Now",
            TransKey.ERROR_EMPTY_FIELDS to "Please fill all input fields!",
            TransKey.ERROR_PASS_MISMATCH to "Password confirmation does not match!",
            TransKey.ERROR_USER_EXISTS to "Username is already registered!",
            TransKey.ERROR_INVALID_CREDENTIALS to "Invalid username or password!",
            TransKey.SUCCESS_REGISTER to "Account Registered Successfully!",
            TransKey.SUCCESS_LOGIN to "Welcome to Sigma Habit!",
            TransKey.WELCOME_BACK to "Welcome,",
            TransKey.LOGOUT to "Log Out",
            TransKey.LEVEL to "Sigma Level",
            TransKey.SETTINGS to "UI Settings",
            TransKey.SELECT_THEME to "Select Visual Theme",
            TransKey.SELECT_LANG to "Select Language",
            TransKey.SIGMA_LEVEL_BAR to "Sigma Progress",
            TransKey.SIGMA_STREAK to "Streak Tracker",
            TransKey.MOTIVATION_BANNER to "Discipline is the bridge between goals and accomplishment.",
            TransKey.HABIT_TRACKER_TITLE to "Habit Tracker",
            TransKey.ADD_HABIT_TITLE to "Add Habit",
            TransKey.EDIT_HABIT_TITLE to "Edit Habit",
            TransKey.HABIT_NAME_LABEL to "Habit Name",
            TransKey.HABIT_DESC_LABEL to "Description / Notes",
            TransKey.BTN_SAVE to "Save",
            TransKey.BTN_CANCEL to "Cancel",
            TransKey.BTN_DELETE to "Delete",
            TransKey.BTN_EDIT to "Edit",
            TransKey.DAILY_PROGRESS to "Daily Progress",
            TransKey.WEEKLY_PROGRESS to "Weekly Progress",
            TransKey.MONTHLY_PROGRESS to "Monthly Progress",
            TransKey.HABIT_STATS to "Habit Stats",
            TransKey.STREAK_DAYS to "Consecutive Streak",
            TransKey.TOTAL_COMPLETIONS to "Total Completed",
            TransKey.COMPLETION_RATE to "Success Rate",
            TransKey.NO_HABITS_YET to "No habits saved yet. Click the '+' button at the top to add!",
            TransKey.CONFIRM_DELETE_TITLE to "Delete Habit?",
            TransKey.CONFIRM_DELETE_MSG to "Are you sure you want to permanently delete this habit?"
        ),
        AppLanguage.JAPANESE to mapOf(
            TransKey.APP_TITLE to "シグマ ハビット アルティメット",
            TransKey.APP_SUBTITLE to "自己管理能力を神レベルまで高める",
            TransKey.LOGIN_TITLE to "シグマ ログイン",
            TransKey.LOGIN_SUBTITLE to "アカウントにログインしてください。",
            TransKey.USERNAME_LABEL to "ユーザー名",
            TransKey.PASSWORD_LABEL to "パスワード",
            TransKey.CONFIRM_PASSWORD_LABEL to "パスワード再確認",
            TransKey.BTN_LOGIN to "ログインする",
            TransKey.BTN_REGISTER to "アカウント作成",
            TransKey.GOTO_REGISTER to "アカウントをお持ちでない方？ 新規登録",
            TransKey.GOTO_LOGIN to "アカウントをすでにお持ちの方？ ログイン",
            TransKey.ERROR_EMPTY_FIELDS to "すべての項目を入力してください！",
            TransKey.ERROR_PASS_MISMATCH to "パスワードが一致しません！",
            TransKey.ERROR_USER_EXISTS to "このユーザー名は既に登録されています！",
            TransKey.ERROR_INVALID_CREDENTIALS to "ユーザー名またはパスワードが正しくありません！",
            TransKey.SUCCESS_REGISTER to "アカウントの登録に成功しました！",
            TransKey.SUCCESS_LOGIN to "シグマハビットへようこそ！",
            TransKey.WELCOME_BACK to "ようこそ、",
            TransKey.LOGOUT to "ログアウト",
            TransKey.LEVEL to "シグマレベル",
            TransKey.SETTINGS to "UI設定",
            TransKey.SELECT_THEME to "ビジュアルテーマの選択",
            TransKey.SELECT_LANG to "言語の選択",
            TransKey.SIGMA_LEVEL_BAR to "シグマの進捗",
            TransKey.SIGMA_STREAK to "連続日数（ストリーク）",
            TransKey.MOTIVATION_BANNER to "規律こそが勝ち組と負け組を分ける唯一の要素である。",
            TransKey.HABIT_TRACKER_TITLE to "ハビットトラッカー",
            TransKey.ADD_HABIT_TITLE to "習慣の追加",
            TransKey.EDIT_HABIT_TITLE to "習慣の編集",
            TransKey.HABIT_NAME_LABEL to "習慣の名前",
            TransKey.HABIT_DESC_LABEL to "説明 / メモ",
            TransKey.BTN_SAVE to "保存する",
            TransKey.BTN_CANCEL to "キャンセル",
            TransKey.BTN_DELETE to "削除する",
            TransKey.BTN_EDIT to "編集",
            TransKey.DAILY_PROGRESS to "今日の進捗",
            TransKey.WEEKLY_PROGRESS to "今週の進捗",
            TransKey.MONTHLY_PROGRESS to "今月の進捗",
            TransKey.HABIT_STATS to "統計情報",
            TransKey.STREAK_DAYS to "連続達成（ストリーク）",
            TransKey.TOTAL_COMPLETIONS to "累計達成回数",
            TransKey.COMPLETION_RATE to "達成率",
            TransKey.NO_HABITS_YET to "習慣がまだありません。上の「+」ボタンを押して追加しましょう！",
            TransKey.CONFIRM_DELETE_TITLE to "習慣を削除しますか？",
            TransKey.CONFIRM_DELETE_MSG to "この習慣を完全に削除してもよろしいですか？"
        ),
        AppLanguage.GERMAN to mapOf(
            TransKey.APP_TITLE to "Sigma Habit Ultimate",
            TransKey.APP_SUBTITLE to "Steigere deine Selbstdisziplin auf Götter-Ebene",
            TransKey.LOGIN_TITLE to "Sigma Authentifizierung",
            TransKey.LOGIN_SUBTITLE to "Bitte melde dich mit deinem lokalen Konto an.",
            TransKey.USERNAME_LABEL to "Benutzername",
            TransKey.PASSWORD_LABEL to "Passwort",
            TransKey.CONFIRM_PASSWORD_LABEL to "Passwort bestätigen",
            TransKey.BTN_LOGIN to "EINLOGGEN",
            TransKey.BTN_REGISTER to "REGISTRIEREN",
            TransKey.GOTO_REGISTER to "Noch kein Konto? Jetzt registrieren",
            TransKey.GOTO_LOGIN to "Schon ein Konto? Jetzt einloggen",
            TransKey.ERROR_EMPTY_FIELDS to "Bitte füllen Sie alle Felder aus!",
            TransKey.ERROR_PASS_MISMATCH to "Passwortbestätigung stimmt nicht überein!",
            TransKey.ERROR_USER_EXISTS to "Benutzername bereits vergeben!",
            TransKey.ERROR_INVALID_CREDENTIALS to "Ungültiger Benutzername oder Passwort!",
            TransKey.SUCCESS_REGISTER to "Konto erfolgreich registriert!",
            TransKey.SUCCESS_LOGIN to "Willkommen bei Sigma Habit!",
            TransKey.WELCOME_BACK to "Willkommen,",
            TransKey.LOGOUT to "Ausloggen",
            TransKey.LEVEL to "Sigma Niveau",
            TransKey.SETTINGS to "UI-Einstellungen",
            TransKey.SELECT_THEME to "Visuelles Thema wählen",
            TransKey.SELECT_LANG to "Sprache wählen",
            TransKey.SIGMA_LEVEL_BAR to "Sigma Fortschritt",
            TransKey.SIGMA_STREAK to "Streak-Zähler",
            TransKey.MOTIVATION_BANNER to "Disziplin ist die Brücke zwischen Zielen und Erfolg.",
            TransKey.HABIT_TRACKER_TITLE to "Gewohnheiten-Tracker",
            TransKey.ADD_HABIT_TITLE to "Gewohnheit hinzufügen",
            TransKey.EDIT_HABIT_TITLE to "Gewohnheit bearbeiten",
            TransKey.HABIT_NAME_LABEL to "Name der Gewohnheit",
            TransKey.HABIT_DESC_LABEL to "Beschreibung / Notizen",
            TransKey.BTN_SAVE to "Speichern",
            TransKey.BTN_CANCEL to "Abbrechen",
            TransKey.BTN_DELETE to "Löschen",
            TransKey.BTN_EDIT to "Bearbeiten",
            TransKey.DAILY_PROGRESS to "Täglicher Fortschritt",
            TransKey.WEEKLY_PROGRESS to "Wöchentlicher Fortschritt",
            TransKey.MONTHLY_PROGRESS to "Monatlicher Fortschritt",
            TransKey.HABIT_STATS to "Statistiken",
            TransKey.STREAK_DAYS to "Aktuelle Strähne",
            TransKey.TOTAL_COMPLETIONS to "Gesamte Erledigungen",
            TransKey.COMPLETION_RATE to "Erfolgsquote",
            TransKey.NO_HABITS_YET to "Noch keine Gewohnheiten. Drücke oben auf '+', um eine zu erstellen!",
            TransKey.CONFIRM_DELETE_TITLE to "Gewohnheit löschen?",
            TransKey.CONFIRM_DELETE_MSG to "Möchten Sie diese Gewohnheit wirklich dauerhaft löschen?"
        )
    )

    fun getString(key: TransKey, lang: AppLanguage): String {
        return translations[lang]?.get(key) ?: translations[AppLanguage.ENGLISH]?.get(key) ?: ""
    }
}
